### shamik_april_2
## To test forward pass

In [8]:
from matplotlib import pyplot as plt 
import numpy as np
def sigmoid(x):
    return 1 / (1 + np.e ** -x)
def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    return np.exp(x) / np.sum(np.exp(x), axis=0)


#load dataset and print entry
dataset = np.loadtxt(fname="sample_shuff_train.txt")

X_train = dataset[0,:2]
Y_train = dataset[0,2:]
print X_train
print Y_train

print X_train.shape
print X_train.reshape(1,2).shape

[8.08912204 6.95900924]
[1. 0.]
(2,)
(1, 2)


In [9]:
#create weight matrix
n_input = int(2)
n_hidden = int(3)
n_output = int(2)
hidden_weights = np.random.rand(n_hidden,n_input)
output_weights = np.random.rand(n_output,n_hidden)
print "hidden layer weight matrix:\n",hidden_weights
print "output layer weight matrix:\n",output_weights

hidden layer weight matrix:
[[0.99458833 0.43493998]
 [0.65451407 0.93824934]
 [0.3336242  0.30801018]]
output layer weight matrix:
[[0.8099001  0.7898278  0.14423292]
 [0.16141241 0.11873602 0.96666539]]


In [10]:
input_vector = np.array(X_train, ndmin=2).T
output_vector = np.dot(hidden_weights, input_vector)
print "output of summed input of hidden layer:\n",output_vector
output_vector = sigmoid(output_vector)
print "activated output of hidden layer:\n",output_vector
output_vector = np.dot(output_weights, output_vector)
print "output of summed input to last layer:\n",output_vector
output_vector = softmax(output_vector)
print "activated output of last layer:\n",output_vector

output of summed input of hidden layer:
[[11.07209771]
 [11.82373004]
 [ 4.84217262]]
activated output of hidden layer:
[[0.99998446]
 [0.99999267]
 [0.99217187]]
output of summed input to last layer:
[[1.74281337]
 [1.23924326]]
activated output of last layer:
[[0.62329795]
 [0.37670205]]


In [11]:
expected = np.array(Y_train,ndmin=2).T
print expected
error = np.sum([(expected-output_vector)**2])/2
print error

[[1.]
 [0.]]
0.14190443182641987
